-- CLIENTS Table
CREATE TABLE APP.CLIENTS (
    CLIENT_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100),
    CONSTRAINT PK_CLIENTS PRIMARY KEY (CLIENT_ID)
);

-- TASKS Table
CREATE TABLE APP.TASKS (
    TASK_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    CATEGORY VARCHAR(50),
    PRIORITY VARCHAR(20),
    STATUS VARCHAR(20) DEFAULT 'Pending',
    DUE_DATE DATE,
    CLIENT_ID INT NOT NULL,
    CONSTRAINT PK_TASKS PRIMARY KEY (TASK_ID),
    CONSTRAINT FK_TASKS_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES APP.CLIENTS(CLIENT_ID) ON DELETE CASCADE
);

-- Indexes for better performance
CREATE INDEX IDX_TASKS_CLIENT ON APP.TASKS(CLIENT_ID);
CREATE INDEX IDX_TASKS_DUE_DATE ON APP.TASKS(DUE_DATE);